name: Build ZMK firmware
on: [push, pull_request]
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
    with:
      build_matrix_path: firmware/ZMK/build.yaml
      config_path: firmware/ZMK/config
